
<p>
  <fieldset>
	<legend>zuletzt modifizierte Dokumente</legend>
	<table>
	  <tr>
		<td><img alt="Dokument1" src="/ajax/latest/count/0"></td>
		<td><img alt="Dokument2" src="/ajax/latest/count/1"></td>
	  </tr>
	  <tr>
		<td><img alt="Dokument3" src="/ajax/latest/count/2"></td>
		<td><img alt="Dokument4" src="/ajax/latest/count/3"></td>
	  </tr>
	</table>
</fieldset>
</p>
<p>
  <fieldset>
	<legend>zuletzt gefunden</legend>
	<table>
	  <tr>
		<td><img alt="Dokument1" src="/ajax/lastfound/count/0"></td>
		<td><img alt="Dokument2" src="/ajax/lastfound/count/1"></td>
	  </tr>
	  <tr>
		<td><img alt="Dokument3" src="/ajax/lastfound/count/2"></td>
		<td><img alt="Dokument4" src="/ajax/lastfound/count/3"></td>
	  </tr>
	</table>
</fieldset>
</p>