


<?php
if (Application_Model_User::isLoggedIn()) {
?>

<ul class="nav pull-right">

<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i> <?= Application_Model_User::getIdentity() ?> <b class="caret"></b></a>
	<ul class="dropdown-menu">
		<li><a href="/settings"><i class="icon-edit"></i> Einstellungen</a></li>
		<li><a href="#"><i class="icon-arrow-up"></i> <strong>Upgrade to Premium</strong></a></li>
		<li><a href="/auth/logout"><i class="icon-off"></i> Abmelden</a></li>
	</ul>
	
</li>

</ul>

<? } else { ?>


<form class="navbar-form pull-right form-inline" action="/auth/login" method="post">
  <input type="text" class="input-small" placeholder="Email" name="username">
  <input type="password" class="input-small" placeholder="Password" name="password">
  <label class="checkbox">
    <input type="checkbox"> Remember me
  </label>
  <button type="submit" class="btn">Sign in</button>
</form>

<? } ?>
