<?php $this->headTitle()->append('Willkommen') ?>

<h3>Willkommen in der DeedBox (<a href="http://de.wikipedia.org/wiki/Beta-Version#Beta-Version" target="_blank">beta</a>)</h3>



<div class="row">
    <div class="offset1 span10">
    <dl>
        <dt>Was ist die DeedBox?</dt>
        <dd>Die DeedBox hilft dir beim ordnen deiner Dokumente. Sie erkennt automatisch
        wichtige Merkmale deiner Dokumente und ordnet sie danach selbstständig ein. Dabei
        lernt die DeedBox laufend dazu und nimmt dir mit der Zeit die Arbeit vollständig ab.
        Du kannst deine Dokumente einfach auf einen virtuellen Haufen schmeissen und 
        die DeedBox übernimmt für dich den Rest. Das Auffinden von Dokumenten wird so
        viel einfacher.</dd>

        <dt>Wie geht die DeedBox dabei vor?</dt>
        <dd>Die DeedBox erkennt deine Dokumente anhand von optischen Merkmalen, beispielsweise
        einem Firmenlogo und ordnet sie so einer Absendergruppe zu. Zusätzlich wird der Text
        deines Dokuments noch analysiert um den Dokumententyp festzustellen. Mittels Mustererkennung
        wird dann noch das effektive Dokumentendatum (Absendedatum, Fälligkeitsdatum, etc) ermittelt.</dd>
        
        <dt>Wo legt die DeedBox meine Dokumente ab?</dt>
        <dd>Die DeedBox ist ein reiner Sortierdienst. Deine Dokumente werden nicht in der DeedBox
        gespeichert sondern im bekannten Online-Speicherdienst 
        <a href="http://dropbox.com" target="_blank">Dropbox</a> abgelegt.</dd>
        
        <dt>Was muss ich tun, um die DeedBox zu benutzen</dt>
        <dd>Das ist ganz einfach, <a href="/auth/signup">registriere</a> dich bei der DeedBox
        und verbinde dich nach dem Login mit deinem Dropbox Konto. Wenn du noch kein Dropbox
        Konto hast, kannst du dieses kostenlos <a href="http://db.tt/Eub75pH" target="_blank">hier</a> 
        erstellen. Die DeedBox wird in deiner Dropbox im Ordner Apps einen Unterordner DeedBox anlegen.
        Dort wird die DeedBox eine saubere Ordnerstruktur deiner Dokumente geordnet nach Absender, 
        Dokumentklasse und Datum führen. Neue Dokumente kannst du entweder via DeedBox hochladen oder 
        in deiner Dropbox in den Ordner "Incoming" unsortiert ablegen. Den Rest erledigt die DeedBox für dich.</dd>
        
        <dt>Wie lernt die DeedBox meine Dokumente zu ordnen?</dt>
        <dd>Die DeedBox wird versuchen, alle Dokumente die du ablegen möchtest, möglichst automatisch
        einzuordnen. Kennd die DeedBox ein Firmenlogo nicht, wird sie dich bitten, das Dokument manuell
        zu identifizieren und ein eideutiges optisches Erkennungsmerkmal zu markeiren. Das machst du,
        in dem du einfach einen Rahmen um das Firmenlogo ziehst und den Firmennamen dazuschreibst. Danach
        wird die DeedBox alle Dokumente mit diesem Firmenlogo automatisch zuordnen können. Die DeedBox wird 
        dich via E-Mail benachrichtigen, wenn sie ein Dokument nicht richtig zuordnen konnte. Je mehr du 
        deiner DeedBox beibringst, desto mehr wird sie automatisch erkennen.</dd>
    </div>
</div>

<div>
<a href="/auth/signup">Registrieren</a> | <a href="/auth/home">Login</a>
</div>
