<?php $this->headTitle()->append('Einstellungen') ?>

<?php

if ($this->success) {
    $state = 'Erfolg!';
    $class = 'success';
} else {
    $state = 'Fehler!';
    $class = 'error';
}

?>

<div>
    <h3>Status - <?= $state; ?></h3>

    <div class="alert alert-<?= $class; ?>">
    <? if ($this->success) { ?>
        <b>Erfolgreich</b><br>
        Die Dropbox wurde erfolgreich aktiviert! Du kannst nun die ersten Dokumente mit der DeedBox sortieren lassen, in dem du sie in den Ordner Apps/DeeBox/Incoming in deiner Dropbox ablegst.
        <p><a href="/"><button class="btn btn-success" type="button">Weiter</button></a></p>
    <? } else { ?>
        <b>Unbekannter Fehler</b><br>
        Es wurde ein Fehler bei der Dropbox-Aktivierung festgestellt. Bitte nochmals versuchen!
        <p><a href="/"><button class="btn btn-danger" type="button">Weiter</button></a></p>
    <? } ?>

    </div>

</div>