<?php $this->headTitle()->append('Willkommen') ?>

<?php

if ($this->success === true) {
    $header = 'Aktivierung erfolgt!';
    $bodytext = 'Die Aktivierung war erfolgreich - du wurdest auch sogleich eingeloggt.<br><a href="/">Hier klicken, dann gehts weiter...</a>';
} else {
    $header = 'Fehler!';
    $bodytext = 'Ein Fehler ist passiert - hast du den Link schon geklickt?';
}

?>

<h3><?=$header; ?></h3>

<div class="row">
<p class="offset1 span10">
<?=$bodytext; ?>
</p>
</div>

<div>

</div>
