<?php $this->headTitle()->append('Dokument bearbeiten') ?>
<?php if (count($this->unrecognizedDocuments) > 0): ?>
    <script language="JavaScript" type="text/javascript" src="/js/contentflow.js" load="white deedbox"></script>
    <script language="JavaScript" type="text/javascript" src="/js/ContentFlowAddOn_white.js"></script>
    <script language="Javascript" type="text/javascript" src="/js/ContentFlowAddOn_deedbox.js"></script>
    <script language="JavaScript" type="text/javascript">
        $(document).ready(function() {
            $("#documentForm").change(function() {
                var docId = $('#documentId');
                var docGroup = $('#documentGroup');
                var docSpec = $('#documentSpec');
                var docDate = $('#date');

                $.get('/ajax/editsave' , {document: docId.val(),
                                            group: docGroup.val(),
                                            spec: docSpec.val(),
                                            date: docDate.val()});
            });
        });
    </script>
    <div id="view-content" style="">
        <h3>Bitte untenstehende Dokumente manuell nachbearbeiten</h3>
    </div>

    <div id="documentForm" style="visibility: visible;" class="form-inline"></div>

    <div class="ContentFlow" style="height:650px; background-color: #F4F4EE; padding-top: 50px; padding-bottom: 200px">
    <div class="loadIndicator"><div class="indicator"></div></div>
    <div class="flow">
        <?php $this->target = '/edit/showbig/documentId';
              echo $this->partialLoop('documentPartial.phtml', $this->unrecognizedDocuments) ?>
    </div>
    <div class="globalCaption"></div>
    <div class="scrollbar"><div class="slider"><div class="position"></div></div></div>
    </div>
<?php else: ?>
    <h3>Es müssen keine Dokumenten manuell nachbearbeitet werden</h3>
<?php endif; ?>
