<?php
$this->headTitle()->append('Dokument suchen');

// javascripts
$this->headScript()->appendFile('/js/contentflow.js');
$this->headScript()->appendFile('/js/ContentFlowAddOn_white.js');
$this->headScript()->appendFile('/js/ContentFlowAddOn_deedbox.js');

?>

<div id="view-content" style="">
<h3>Bitte geben sie ihre Suchkriterien ein</h3>
</div>

<div id="searchForm" style="visibility: visible; height: 180px;">
    <p>
        <label for="daterange">Datum zwischen:</label>
        <input type="text" id="daterange" size="50" style="border:0; color:#f6931f; font-weight:bold;" />
    </p>

    <div id="slider-range"></div>
	
    <p>    
        <div id="search-fields"><?= $this->form ?></div>
    </p>    
</div>