<h3>Statistiken zu Dokument <?= $this->docname ?></h3>
<table>
    <tr>
        <td><img width="400" src="/ajax/boxplot/filename/<?= $this->groupstats ?>" /></td>
        <td><img width="400" src="/ajax/boxplot/filename/<?= $this->specstats ?>" /></td>
    </tr>
        <tr>
        <td>Gruppenname: <?= $this->groupName ?></td>
        <td>Klassenname: <?= $this->specName ?></td>
    </tr>
    </tr>
        <tr>
        <td>Treffsicherheit: <?= $this->groupAccuracy ?>%</td>
        <td>Treffsicherheit: <?= $this->specAccuracy ?>%</td>
    </tr>
    <tr>
        <td valign="top"><table>
                <?= $this->partialLoop('statsPartial.phtml', $this->subimage) ?>
            </table>
        </td>
        <td valign="top"><table>
                <?= $this->partialLoop('statsPartial.phtml', $this->docspec) ?>
            </table>
        </td>
    </tr>
</table>


