<?php

$this->headTitle()->append('Dokument suchen');

$this->headScript()->appendFile('/js/contentflow.js');
$this->headScript()->appendFile('/js/ContentFlowAddOn_white.js');
$this->headScript()->appendFile('/js/ContentFlowAddOn_deedbox.js');

?>

<div id="view-content" style="">
<h3>Es wurden <?= $this->resultCount ?> Resultate gefunden</h3>
</div>

<div id="searchForm">
    <p>
        <label for="daterange">Datum zwischen:</label>
        <input type="text" id="daterange" size="50" style="border:0; color:#f6931f; font-weight:bold;" />
    </p>
    <div id="slider-range"></div>
	
    <div id="search-fields"><?= $this->form ?></div>
</div>
<a id="docstats" target="_blank">Statistiken zum angezeigten Dokument</a>
|
<a id="editdoc" target="_blank">Dokument bearbeiten</a>
<div class="ContentFlow" style="height:650px; background-color: #F4F4EE; padding-top: 10px; padding-bottom: 200px">
    <div class="loadIndicator"><div class="indicator"></div></div>
    <div class="flow">
                <?= $this->partialLoop('documentPartial.phtml', $this->flowContent) ?>
    </div>
    <div class="globalCaption"></div>
    <div class="scrollbar"><div class="slider"><div class="position"></div></div></div>
</div>